DEFAULT_THEME_NAME = "termin"

INTERFACE_KEYS = (
    "bg",
    "panel",
    "panel_alt",
    "ink",
    "muted",
    "accent",
    "accent_strong",
    "border",
    "success",
    "grid",
    "bg_top",
    "bg_mid",
    "bg_bottom",
    "header_bg",
    "menu_bg",
    "menu_shadow",
)

DEFAULT_INTERFACE = {
    "dark": {
        "bg": "#0b0d12",
        "panel": "#151a22",
        "panel_alt": "#10141b",
        "ink": "#e6edf3",
        "muted": "#9aa3ad",
        "accent": "#4cc9f0",
        "accent_strong": "#00b4d8",
        "border": "#232a36",
        "success": "#6ee7b7",
        "grid": "rgba(255, 255, 255, 0.06)",
        "bg_top": "#141a24",
        "bg_mid": "#0b0d12",
        "bg_bottom": "#0a0d12",
        "header_bg": "color-mix(in srgb, #10141b 88%, transparent)",
        "menu_bg": "rgba(17, 21, 28, 0.96)",
        "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.34)",
    },
    "light": {
        "bg": "#eef3f8",
        "panel": "#ffffff",
        "panel_alt": "#f7fafc",
        "ink": "#17202b",
        "muted": "#5f6b7a",
        "accent": "#1677c8",
        "accent_strong": "#0b5ea4",
        "border": "#d7e0ea",
        "success": "#15803d",
        "grid": "rgba(23, 32, 43, 0.08)",
        "bg_top": "#ffffff",
        "bg_mid": "#f5f8fc",
        "bg_bottom": "#eef3f8",
        "header_bg": "color-mix(in srgb, #f7fafc 90%, transparent)",
        "menu_bg": "rgba(255, 255, 255, 0.98)",
        "menu_shadow": "0 16px 30px rgba(15, 23, 42, 0.12)",
    },
}

THEME_DEFINITIONS = (
    {
        "key": "termin",
        "label": "Termin",
        "font_family": '"Space Grotesk", "IBM Plex Sans", "Segoe UI", sans-serif',
        "palette": (
            "#1f77b4",
            "#ff7f0e",
            "#2ca02c",
            "#d62728",
            "#9467bd",
            "#8c564b",
            "#e377c2",
            "#7f7f7f",
            "#bcbd22",
            "#17becf",
        ),
        "ui": {
            "dark": {
                "bg": "#0b0d12",
                "panel": "#151a22",
                "panel_alt": "#10141b",
                "ink": "#e6edf3",
                "muted": "#9aa3ad",
                "accent": "#4cc9f0",
                "accent_strong": "#00b4d8",
                "border": "#232a36",
                "success": "#6ee7b7",
                "grid": "rgba(255, 255, 255, 0.06)",
                "bg_top": "#141a24",
                "bg_mid": "#0b0d12",
                "bg_bottom": "#0a0d12",
                "header_bg": "color-mix(in srgb, #10141b 88%, transparent)",
                "menu_bg": "rgba(17, 21, 28, 0.96)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.34)",
            },
            "light": {
                "bg": "#eef3f8",
                "panel": "#ffffff",
                "panel_alt": "#f7fafc",
                "ink": "#17202b",
                "muted": "#5f6b7a",
                "accent": "#1677c8",
                "accent_strong": "#0b5ea4",
                "border": "#d7e0ea",
                "success": "#15803d",
                "grid": "rgba(23, 32, 43, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f5f8fc",
                "bg_bottom": "#eef3f8",
                "header_bg": "color-mix(in srgb, #f7fafc 90%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(15, 23, 42, 0.12)",
            },
        },
    },
    {
        "key": "library",
        "label": "Library",
        "font_family": '"Space Grotesk", "IBM Plex Sans", "Segoe UI", sans-serif',
        "palette": (
            "#355070",
            "#6d597a",
            "#b56576",
            "#e56b6f",
            "#eaac8b",
            "#7f5539",
            "#b08968",
            "#ddb892",
            "#a4c3b2",
            "#588157",
        ),
        "ui": {
            "dark": {
                "bg": "#15110f",
                "panel": "#1f1815",
                "panel_alt": "#191310",
                "ink": "#f2e6db",
                "muted": "#b8a79a",
                "accent": "#c6905b",
                "accent_strong": "#e0ad78",
                "border": "#3a2d27",
                "success": "#8bcf9d",
                "grid": "rgba(242, 230, 219, 0.07)",
                "bg_top": "#2b1e18",
                "bg_mid": "#15110f",
                "bg_bottom": "#100c0a",
                "header_bg": "color-mix(in srgb, #191310 90%, transparent)",
                "menu_bg": "rgba(31, 24, 21, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.38)",
            },
            "light": {
                "bg": "#f7f1ea",
                "panel": "#fffaf4",
                "panel_alt": "#f5ede2",
                "ink": "#3a2d27",
                "muted": "#766458",
                "accent": "#9a5f2f",
                "accent_strong": "#7d4a22",
                "border": "#ddcbbd",
                "success": "#3f7d4d",
                "grid": "rgba(58, 45, 39, 0.08)",
                "bg_top": "#fffdf9",
                "bg_mid": "#faf3eb",
                "bg_bottom": "#f7f1ea",
                "header_bg": "color-mix(in srgb, #f5ede2 92%, transparent)",
                "menu_bg": "rgba(255, 250, 244, 0.98)",
                "menu_shadow": "0 16px 30px rgba(58, 45, 39, 0.12)",
            },
        },
    },
    {
        "key": "seminar",
        "label": "Seminar",
        "font_family": '"Space Grotesk", "IBM Plex Sans", "Segoe UI", sans-serif',
        "palette": (
            "#264653",
            "#2a9d8f",
            "#8ab17d",
            "#e9c46a",
            "#f4a261",
            "#e76f51",
            "#577590",
            "#90be6d",
            "#f94144",
            "#277da1",
        ),
        "ui": {
            "dark": {
                "bg": "#0f171b",
                "panel": "#152127",
                "panel_alt": "#111a1f",
                "ink": "#e5f0ef",
                "muted": "#97aaa8",
                "accent": "#2a9d8f",
                "accent_strong": "#3fb8a8",
                "border": "#26363b",
                "success": "#8ab17d",
                "grid": "rgba(229, 240, 239, 0.06)",
                "bg_top": "#1a2b31",
                "bg_mid": "#0f171b",
                "bg_bottom": "#0b1013",
                "header_bg": "color-mix(in srgb, #111a1f 90%, transparent)",
                "menu_bg": "rgba(21, 33, 39, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.36)",
            },
            "light": {
                "bg": "#edf7f5",
                "panel": "#ffffff",
                "panel_alt": "#f3fbf9",
                "ink": "#17353a",
                "muted": "#58727a",
                "accent": "#1f7f74",
                "accent_strong": "#165f57",
                "border": "#d5e6e3",
                "success": "#4b8b58",
                "grid": "rgba(23, 53, 58, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f4fbfa",
                "bg_bottom": "#edf7f5",
                "header_bg": "color-mix(in srgb, #f3fbf9 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(23, 53, 58, 0.12)",
            },
        },
    },
    {
        "key": "archive",
        "label": "Archive",
        "font_family": '"Space Grotesk", "IBM Plex Sans", "Segoe UI", sans-serif',
        "palette": (
            "#2f3e46",
            "#354f52",
            "#52796f",
            "#84a98c",
            "#cad2c5",
            "#8d6a9f",
            "#c08497",
            "#dda15e",
            "#bc6c25",
            "#6b705c",
        ),
        "ui": {
            "dark": {
                "bg": "#111517",
                "panel": "#171d20",
                "panel_alt": "#13181b",
                "ink": "#e8ece6",
                "muted": "#9ea8a0",
                "accent": "#84a98c",
                "accent_strong": "#9bb7a1",
                "border": "#2b3337",
                "success": "#86c28b",
                "grid": "rgba(232, 236, 230, 0.06)",
                "bg_top": "#20282b",
                "bg_mid": "#111517",
                "bg_bottom": "#0c1011",
                "header_bg": "color-mix(in srgb, #13181b 90%, transparent)",
                "menu_bg": "rgba(23, 29, 32, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.38)",
            },
            "light": {
                "bg": "#f2f4ef",
                "panel": "#ffffff",
                "panel_alt": "#f7f8f4",
                "ink": "#253238",
                "muted": "#617171",
                "accent": "#5b8573",
                "accent_strong": "#446858",
                "border": "#d9dfd7",
                "success": "#4d8d57",
                "grid": "rgba(37, 50, 56, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f8faf6",
                "bg_bottom": "#f2f4ef",
                "header_bg": "color-mix(in srgb, #f7f8f4 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(37, 50, 56, 0.12)",
            },
        },
    },
    {
        "key": "lab",
        "label": "Lab",
        "palette": (
            "#006d77",
            "#83c5be",
            "#edf6f9",
            "#ffddd2",
            "#e29578",
            "#3a86ff",
            "#8338ec",
            "#ff006e",
            "#fb5607",
            "#ffbe0b",
        ),
        "ui": {
            "dark": {
                "bg": "#0b1020",
                "panel": "#12192d",
                "panel_alt": "#0d1324",
                "ink": "#e7f0ff",
                "muted": "#99a9c7",
                "accent": "#3a86ff",
                "accent_strong": "#5b9dff",
                "border": "#202a45",
                "success": "#5ed6a3",
                "grid": "rgba(231, 240, 255, 0.06)",
                "bg_top": "#1b2b57",
                "bg_mid": "#0b1020",
                "bg_bottom": "#090d18",
                "header_bg": "color-mix(in srgb, #0d1324 90%, transparent)",
                "menu_bg": "rgba(18, 25, 45, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.42)",
            },
            "light": {
                "bg": "#eef5ff",
                "panel": "#ffffff",
                "panel_alt": "#f4f8ff",
                "ink": "#15233f",
                "muted": "#5c6f94",
                "accent": "#2563eb",
                "accent_strong": "#1d4ed8",
                "border": "#d8e3f7",
                "success": "#0f9f67",
                "grid": "rgba(21, 35, 63, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f5f9ff",
                "bg_bottom": "#eef5ff",
                "header_bg": "color-mix(in srgb, #f4f8ff 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(21, 35, 63, 0.12)",
            },
        },
    },
    {
        "key": "chalk",
        "label": "Chalk",
        "palette": (
            "#3d5a80",
            "#98c1d9",
            "#e0fbfc",
            "#ee6c4d",
            "#293241",
            "#5c677d",
            "#7d8597",
            "#adb5bd",
            "#52b788",
            "#40916c",
        ),
        "ui": {
            "dark": {
                "bg": "#10141a",
                "panel": "#171d27",
                "panel_alt": "#131821",
                "ink": "#edf3f8",
                "muted": "#a0acb8",
                "accent": "#98c1d9",
                "accent_strong": "#b2d3e6",
                "border": "#2a3442",
                "success": "#6dc89d",
                "grid": "rgba(237, 243, 248, 0.06)",
                "bg_top": "#223247",
                "bg_mid": "#10141a",
                "bg_bottom": "#0b0f14",
                "header_bg": "color-mix(in srgb, #131821 90%, transparent)",
                "menu_bg": "rgba(23, 29, 39, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.38)",
            },
            "light": {
                "bg": "#f3f7fb",
                "panel": "#ffffff",
                "panel_alt": "#f7fafd",
                "ink": "#1f2f42",
                "muted": "#627287",
                "accent": "#3d6f9b",
                "accent_strong": "#2d577b",
                "border": "#dbe4ee",
                "success": "#2f8f66",
                "grid": "rgba(31, 47, 66, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f8fbff",
                "bg_bottom": "#f3f7fb",
                "header_bg": "color-mix(in srgb, #f7fafd 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(31, 47, 66, 0.12)",
            },
        },
    },
    {
        "key": "field",
        "label": "Field",
        "palette": (
            "#386641",
            "#6a994e",
            "#a7c957",
            "#f2e8cf",
            "#bc4749",
            "#4361ee",
            "#4cc9f0",
            "#4895ef",
            "#f72585",
            "#7209b7",
        ),
        "ui": {
            "dark": {
                "bg": "#11160f",
                "panel": "#1a2217",
                "panel_alt": "#141b12",
                "ink": "#edf4e8",
                "muted": "#a2b099",
                "accent": "#6a994e",
                "accent_strong": "#84b467",
                "border": "#2c3628",
                "success": "#9fd86f",
                "grid": "rgba(237, 244, 232, 0.06)",
                "bg_top": "#263520",
                "bg_mid": "#11160f",
                "bg_bottom": "#0d110b",
                "header_bg": "color-mix(in srgb, #141b12 90%, transparent)",
                "menu_bg": "rgba(26, 34, 23, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.38)",
            },
            "light": {
                "bg": "#f3f8ef",
                "panel": "#ffffff",
                "panel_alt": "#f7fbf4",
                "ink": "#23331f",
                "muted": "#667660",
                "accent": "#4f7f38",
                "accent_strong": "#3d642b",
                "border": "#dbe7d3",
                "success": "#5d9c3b",
                "grid": "rgba(35, 51, 31, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f8fcf5",
                "bg_bottom": "#f3f8ef",
                "header_bg": "color-mix(in srgb, #f7fbf4 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(35, 51, 31, 0.12)",
            },
        },
    },
    {
        "key": "studio",
        "label": "Studio",
        "palette": (
            "#22223b",
            "#4a4e69",
            "#9a8c98",
            "#c9ada7",
            "#f2e9e4",
            "#d4a373",
            "#6d597a",
            "#b56576",
            "#e56b6f",
            "#eaac8b",
        ),
        "ui": {
            "dark": {
                "bg": "#120f17",
                "panel": "#1b1623",
                "panel_alt": "#15111d",
                "ink": "#f1ebf4",
                "muted": "#b0a0b6",
                "accent": "#b56576",
                "accent_strong": "#cf7f8f",
                "border": "#31273a",
                "success": "#7dc8a4",
                "grid": "rgba(241, 235, 244, 0.06)",
                "bg_top": "#2a2034",
                "bg_mid": "#120f17",
                "bg_bottom": "#0d0a12",
                "header_bg": "color-mix(in srgb, #15111d 90%, transparent)",
                "menu_bg": "rgba(27, 22, 35, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.4)",
            },
            "light": {
                "bg": "#faf4f6",
                "panel": "#ffffff",
                "panel_alt": "#fdf7f8",
                "ink": "#332737",
                "muted": "#74657a",
                "accent": "#9f4f61",
                "accent_strong": "#803b4c",
                "border": "#eadbdf",
                "success": "#3f8f6d",
                "grid": "rgba(51, 39, 55, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fff8fa",
                "bg_bottom": "#faf4f6",
                "header_bg": "color-mix(in srgb, #fdf7f8 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(51, 39, 55, 0.12)",
            },
        },
    },
    {
        "key": "glacier",
        "label": "Glacier",
        "palette": (
            "#1d3557",
            "#457b9d",
            "#a8dadc",
            "#e0fbfc",
            "#f1faee",
            "#8ecae6",
            "#219ebc",
            "#023047",
            "#90e0ef",
            "#caf0f8",
        ),
        "ui": {
            "dark": {
                "bg": "#09131a",
                "panel": "#10202b",
                "panel_alt": "#0c1821",
                "ink": "#eaf7fb",
                "muted": "#9db7c1",
                "accent": "#5ab6d6",
                "accent_strong": "#8ed8ef",
                "border": "#203746",
                "success": "#7bd0b0",
                "grid": "rgba(234, 247, 251, 0.06)",
                "bg_top": "#173646",
                "bg_mid": "#09131a",
                "bg_bottom": "#060d12",
                "header_bg": "color-mix(in srgb, #0c1821 90%, transparent)",
                "menu_bg": "rgba(16, 32, 43, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.4)",
            },
            "light": {
                "bg": "#eef8fb",
                "panel": "#ffffff",
                "panel_alt": "#f5fbfd",
                "ink": "#163040",
                "muted": "#62808f",
                "accent": "#2c7da0",
                "accent_strong": "#1f5f7b",
                "border": "#d8e8ef",
                "success": "#2f8f70",
                "grid": "rgba(22, 48, 64, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f6fcfe",
                "bg_bottom": "#eef8fb",
                "header_bg": "color-mix(in srgb, #f5fbfd 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(22, 48, 64, 0.12)",
            },
        },
    },
    {
        "key": "ocean",
        "label": "Ocean",
        "palette": (
            "#003049",
            "#005f73",
            "#0a9396",
            "#94d2bd",
            "#e9d8a6",
            "#ee9b00",
            "#ca6702",
            "#bb3e03",
            "#ae2012",
            "#9b2226",
        ),
        "ui": {
            "dark": {
                "bg": "#08121a",
                "panel": "#0f1e28",
                "panel_alt": "#0b1720",
                "ink": "#e6f2f5",
                "muted": "#95aeb7",
                "accent": "#0a9396",
                "accent_strong": "#37b8b7",
                "border": "#1d3542",
                "success": "#73c69d",
                "grid": "rgba(230, 242, 245, 0.06)",
                "bg_top": "#124056",
                "bg_mid": "#08121a",
                "bg_bottom": "#050b10",
                "header_bg": "color-mix(in srgb, #0b1720 90%, transparent)",
                "menu_bg": "rgba(15, 30, 40, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.4)",
            },
            "light": {
                "bg": "#eef7f8",
                "panel": "#ffffff",
                "panel_alt": "#f4fbfb",
                "ink": "#17313a",
                "muted": "#5c7780",
                "accent": "#0b7285",
                "accent_strong": "#07596a",
                "border": "#d7e7ea",
                "success": "#2d8a62",
                "grid": "rgba(23, 49, 58, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f5fcfc",
                "bg_bottom": "#eef7f8",
                "header_bg": "color-mix(in srgb, #f4fbfb 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(23, 49, 58, 0.12)",
            },
        },
    },
    {
        "key": "forest",
        "label": "Forest",
        "palette": (
            "#14342b",
            "#2d6a4f",
            "#40916c",
            "#52b788",
            "#74c69d",
            "#95d5b2",
            "#b7e4c7",
            "#d8f3dc",
            "#6b705c",
            "#a3b18a",
        ),
        "ui": {
            "dark": {
                "bg": "#0d130f",
                "panel": "#141d17",
                "panel_alt": "#101713",
                "ink": "#edf4ee",
                "muted": "#a0b19f",
                "accent": "#52b788",
                "accent_strong": "#74c69d",
                "border": "#263128",
                "success": "#95d5b2",
                "grid": "rgba(237, 244, 238, 0.06)",
                "bg_top": "#213529",
                "bg_mid": "#0d130f",
                "bg_bottom": "#090d0a",
                "header_bg": "color-mix(in srgb, #101713 90%, transparent)",
                "menu_bg": "rgba(20, 29, 23, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.38)",
            },
            "light": {
                "bg": "#f2f8f3",
                "panel": "#ffffff",
                "panel_alt": "#f7fbf7",
                "ink": "#223328",
                "muted": "#62756a",
                "accent": "#2f855a",
                "accent_strong": "#236946",
                "border": "#dce8de",
                "success": "#3a9d63",
                "grid": "rgba(34, 51, 40, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f8fcf8",
                "bg_bottom": "#f2f8f3",
                "header_bg": "color-mix(in srgb, #f7fbf7 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(34, 51, 40, 0.12)",
            },
        },
    },
    {
        "key": "sage",
        "label": "Sage",
        "palette": (
            "#5f7161",
            "#6d8b74",
            "#8fa998",
            "#b6c4b6",
            "#d0e7d2",
            "#efead8",
            "#c7b198",
            "#a4907c",
            "#7d7463",
            "#5b5346",
        ),
        "ui": {
            "dark": {
                "bg": "#121511",
                "panel": "#1a1f18",
                "panel_alt": "#151914",
                "ink": "#eff2ea",
                "muted": "#a8afa0",
                "accent": "#8fa998",
                "accent_strong": "#b6c4b6",
                "border": "#2d342b",
                "success": "#8eb58f",
                "grid": "rgba(239, 242, 234, 0.06)",
                "bg_top": "#30392e",
                "bg_mid": "#121511",
                "bg_bottom": "#0c0f0b",
                "header_bg": "color-mix(in srgb, #151914 90%, transparent)",
                "menu_bg": "rgba(26, 31, 24, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.38)",
            },
            "light": {
                "bg": "#f6f8f3",
                "panel": "#ffffff",
                "panel_alt": "#fafbf7",
                "ink": "#2f352c",
                "muted": "#6f786b",
                "accent": "#6d8b74",
                "accent_strong": "#57715d",
                "border": "#e1e7dd",
                "success": "#5d8a5e",
                "grid": "rgba(47, 53, 44, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fbfcf9",
                "bg_bottom": "#f6f8f3",
                "header_bg": "color-mix(in srgb, #fafbf7 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(47, 53, 44, 0.12)",
            },
        },
    },
    {
        "key": "desert",
        "label": "Desert",
        "palette": (
            "#6c584c",
            "#a98467",
            "#adc178",
            "#dde5b6",
            "#f0ead2",
            "#bc6c25",
            "#dda15e",
            "#e09f3e",
            "#9c6644",
            "#7f5539",
        ),
        "ui": {
            "dark": {
                "bg": "#16110d",
                "panel": "#211914",
                "panel_alt": "#1a140f",
                "ink": "#f4ede2",
                "muted": "#b6a694",
                "accent": "#dda15e",
                "accent_strong": "#f0bc7b",
                "border": "#3a2d23",
                "success": "#9ac07b",
                "grid": "rgba(244, 237, 226, 0.06)",
                "bg_top": "#3b281b",
                "bg_mid": "#16110d",
                "bg_bottom": "#0f0b08",
                "header_bg": "color-mix(in srgb, #1a140f 90%, transparent)",
                "menu_bg": "rgba(33, 25, 20, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.4)",
            },
            "light": {
                "bg": "#faf5ec",
                "panel": "#ffffff",
                "panel_alt": "#fffaf2",
                "ink": "#3f2f25",
                "muted": "#7f6a5a",
                "accent": "#bc6c25",
                "accent_strong": "#97541b",
                "border": "#eadcc8",
                "success": "#668f4a",
                "grid": "rgba(63, 47, 37, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fffbf5",
                "bg_bottom": "#faf5ec",
                "header_bg": "color-mix(in srgb, #fffaf2 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(63, 47, 37, 0.12)",
            },
        },
    },
    {
        "key": "sunrise",
        "label": "Sunrise",
        "palette": (
            "#355070",
            "#6d597a",
            "#b56576",
            "#e56b6f",
            "#eaac8b",
            "#f4a261",
            "#e9c46a",
            "#ffb703",
            "#fb8500",
            "#d62828",
        ),
        "ui": {
            "dark": {
                "bg": "#161017",
                "panel": "#201821",
                "panel_alt": "#191218",
                "ink": "#f7edf1",
                "muted": "#bda5b0",
                "accent": "#e56b6f",
                "accent_strong": "#ffb4a2",
                "border": "#382734",
                "success": "#8ecf88",
                "grid": "rgba(247, 237, 241, 0.06)",
                "bg_top": "#5d3558",
                "bg_mid": "#161017",
                "bg_bottom": "#0f0a10",
                "header_bg": "color-mix(in srgb, #191218 90%, transparent)",
                "menu_bg": "rgba(32, 24, 33, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.4)",
            },
            "light": {
                "bg": "#fff5f5",
                "panel": "#ffffff",
                "panel_alt": "#fff8f7",
                "ink": "#432433",
                "muted": "#816676",
                "accent": "#cf4f58",
                "accent_strong": "#a63c47",
                "border": "#f1dde0",
                "success": "#5d9a56",
                "grid": "rgba(67, 36, 51, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fff9f7",
                "bg_bottom": "#fff5f5",
                "header_bg": "color-mix(in srgb, #fff8f7 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(67, 36, 51, 0.12)",
            },
        },
    },
    {
        "key": "ember",
        "label": "Ember",
        "palette": (
            "#2b2d42",
            "#8d99ae",
            "#edf2f4",
            "#ef233c",
            "#d90429",
            "#f77f00",
            "#fcbf49",
            "#eae2b7",
            "#9d0208",
            "#6a040f",
        ),
        "ui": {
            "dark": {
                "bg": "#140d0d",
                "panel": "#1f1414",
                "panel_alt": "#180f0f",
                "ink": "#f7efed",
                "muted": "#bea8a2",
                "accent": "#ef233c",
                "accent_strong": "#f77f00",
                "border": "#382323",
                "success": "#8acb7b",
                "grid": "rgba(247, 239, 237, 0.06)",
                "bg_top": "#4b1e1e",
                "bg_mid": "#140d0d",
                "bg_bottom": "#0e0808",
                "header_bg": "color-mix(in srgb, #180f0f 90%, transparent)",
                "menu_bg": "rgba(31, 20, 20, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.42)",
            },
            "light": {
                "bg": "#fff5f2",
                "panel": "#ffffff",
                "panel_alt": "#fff8f6",
                "ink": "#401f1f",
                "muted": "#7f6660",
                "accent": "#d62839",
                "accent_strong": "#b31f2f",
                "border": "#f0ddd8",
                "success": "#5a994f",
                "grid": "rgba(64, 31, 31, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fff9f7",
                "bg_bottom": "#fff5f2",
                "header_bg": "color-mix(in srgb, #fff8f6 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(64, 31, 31, 0.12)",
            },
        },
    },
    {
        "key": "graphite",
        "label": "Graphite",
        "palette": (
            "#111827",
            "#1f2937",
            "#374151",
            "#4b5563",
            "#6b7280",
            "#9ca3af",
            "#d1d5db",
            "#e5e7eb",
            "#94a3b8",
            "#64748b",
        ),
        "ui": {
            "dark": {
                "bg": "#0b0c0f",
                "panel": "#13151a",
                "panel_alt": "#0f1115",
                "ink": "#eef1f5",
                "muted": "#a3aab4",
                "accent": "#94a3b8",
                "accent_strong": "#cbd5e1",
                "border": "#272d36",
                "success": "#7bc18a",
                "grid": "rgba(238, 241, 245, 0.06)",
                "bg_top": "#1d232d",
                "bg_mid": "#0b0c0f",
                "bg_bottom": "#07080a",
                "header_bg": "color-mix(in srgb, #0f1115 90%, transparent)",
                "menu_bg": "rgba(19, 21, 26, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.42)",
            },
            "light": {
                "bg": "#f5f6f8",
                "panel": "#ffffff",
                "panel_alt": "#fafbfc",
                "ink": "#20242b",
                "muted": "#666f7b",
                "accent": "#475569",
                "accent_strong": "#334155",
                "border": "#e2e6ea",
                "success": "#4f8d62",
                "grid": "rgba(32, 36, 43, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fbfcfd",
                "bg_bottom": "#f5f6f8",
                "header_bg": "color-mix(in srgb, #fafbfc 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(32, 36, 43, 0.12)",
            },
        },
    },
    {
        "key": "slate",
        "label": "Slate",
        "palette": (
            "#0f172a",
            "#1e293b",
            "#334155",
            "#475569",
            "#64748b",
            "#94a3b8",
            "#cbd5e1",
            "#e2e8f0",
            "#38bdf8",
            "#22c55e",
        ),
        "ui": {
            "dark": {
                "bg": "#0a0f18",
                "panel": "#101826",
                "panel_alt": "#0d1420",
                "ink": "#edf3fb",
                "muted": "#9eacbd",
                "accent": "#38bdf8",
                "accent_strong": "#7dd3fc",
                "border": "#202a3a",
                "success": "#5fc97e",
                "grid": "rgba(237, 243, 251, 0.06)",
                "bg_top": "#1a2944",
                "bg_mid": "#0a0f18",
                "bg_bottom": "#060912",
                "header_bg": "color-mix(in srgb, #0d1420 90%, transparent)",
                "menu_bg": "rgba(16, 24, 38, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.42)",
            },
            "light": {
                "bg": "#f2f6fb",
                "panel": "#ffffff",
                "panel_alt": "#f8fafc",
                "ink": "#1d2939",
                "muted": "#617084",
                "accent": "#0284c7",
                "accent_strong": "#0369a1",
                "border": "#dde5ee",
                "success": "#2f8f54",
                "grid": "rgba(29, 41, 57, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fafcff",
                "bg_bottom": "#f2f6fb",
                "header_bg": "color-mix(in srgb, #f8fafc 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(29, 41, 57, 0.12)",
            },
        },
    },
    {
        "key": "plum",
        "label": "Plum",
        "palette": (
            "#231942",
            "#5e548e",
            "#9f86c0",
            "#be95c4",
            "#e0b1cb",
            "#f28482",
            "#f6bd60",
            "#84a59d",
            "#f5cac3",
            "#6d597a",
        ),
        "ui": {
            "dark": {
                "bg": "#120d19",
                "panel": "#1b1524",
                "panel_alt": "#15101d",
                "ink": "#f4eef7",
                "muted": "#b4a7bc",
                "accent": "#9f86c0",
                "accent_strong": "#c8b6e2",
                "border": "#30263a",
                "success": "#8fca9f",
                "grid": "rgba(244, 238, 247, 0.06)",
                "bg_top": "#35254b",
                "bg_mid": "#120d19",
                "bg_bottom": "#0c0912",
                "header_bg": "color-mix(in srgb, #15101d 90%, transparent)",
                "menu_bg": "rgba(27, 21, 36, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.4)",
            },
            "light": {
                "bg": "#faf5fb",
                "panel": "#ffffff",
                "panel_alt": "#fdf8fd",
                "ink": "#342845",
                "muted": "#756884",
                "accent": "#7c5ca8",
                "accent_strong": "#624887",
                "border": "#ebdff0",
                "success": "#568f64",
                "grid": "rgba(52, 40, 69, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fef9fe",
                "bg_bottom": "#faf5fb",
                "header_bg": "color-mix(in srgb, #fdf8fd 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(52, 40, 69, 0.12)",
            },
        },
    },
    {
        "key": "orchard",
        "label": "Orchard",
        "palette": (
            "#283618",
            "#606c38",
            "#7f8f3c",
            "#bc6c25",
            "#dda15e",
            "#fefae0",
            "#d00000",
            "#e85d04",
            "#ffba08",
            "#6a040f",
        ),
        "ui": {
            "dark": {
                "bg": "#13120c",
                "panel": "#1d1b13",
                "panel_alt": "#16150f",
                "ink": "#f5f0e3",
                "muted": "#b6ab93",
                "accent": "#bc6c25",
                "accent_strong": "#dda15e",
                "border": "#352e21",
                "success": "#8eb05f",
                "grid": "rgba(245, 240, 227, 0.06)",
                "bg_top": "#3c341c",
                "bg_mid": "#13120c",
                "bg_bottom": "#0d0c08",
                "header_bg": "color-mix(in srgb, #16150f 90%, transparent)",
                "menu_bg": "rgba(29, 27, 19, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.4)",
            },
            "light": {
                "bg": "#fcf8ef",
                "panel": "#ffffff",
                "panel_alt": "#fffbf4",
                "ink": "#3d331f",
                "muted": "#7e7058",
                "accent": "#9c5d21",
                "accent_strong": "#7f4919",
                "border": "#ede2ce",
                "success": "#668a44",
                "grid": "rgba(61, 51, 31, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fffdf8",
                "bg_bottom": "#fcf8ef",
                "header_bg": "color-mix(in srgb, #fffbf4 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(61, 51, 31, 0.12)",
            },
        },
    },
    {
        "key": "midnight",
        "label": "Midnight",
        "palette": (
            "#03045e",
            "#023e8a",
            "#0077b6",
            "#0096c7",
            "#00b4d8",
            "#48cae4",
            "#90e0ef",
            "#ade8f4",
            "#caf0f8",
            "#5e60ce",
        ),
        "ui": {
            "dark": {
                "bg": "#070814",
                "panel": "#0f1323",
                "panel_alt": "#0b0f1d",
                "ink": "#edf2ff",
                "muted": "#9faad4",
                "accent": "#48cae4",
                "accent_strong": "#90e0ef",
                "border": "#1d2640",
                "success": "#64c99a",
                "grid": "rgba(237, 242, 255, 0.06)",
                "bg_top": "#16214a",
                "bg_mid": "#070814",
                "bg_bottom": "#04060d",
                "header_bg": "color-mix(in srgb, #0b0f1d 90%, transparent)",
                "menu_bg": "rgba(15, 19, 35, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.44)",
            },
            "light": {
                "bg": "#f0f6ff",
                "panel": "#ffffff",
                "panel_alt": "#f7fbff",
                "ink": "#1b2550",
                "muted": "#5f6da1",
                "accent": "#0077b6",
                "accent_strong": "#005b8d",
                "border": "#d9e4f7",
                "success": "#2f8f61",
                "grid": "rgba(27, 37, 80, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f8fbff",
                "bg_bottom": "#f0f6ff",
                "header_bg": "color-mix(in srgb, #f7fbff 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(27, 37, 80, 0.12)",
            },
        },
    },
    {
        "key": "neon",
        "label": "Neon",
        "palette": (
            "#0f0f0f",
            "#00f5d4",
            "#00bbf9",
            "#3a86ff",
            "#8338ec",
            "#ff006e",
            "#fb5607",
            "#ffbe0b",
            "#8ac926",
            "#f15bb5",
        ),
        "ui": {
            "dark": {
                "bg": "#09090b",
                "panel": "#111117",
                "panel_alt": "#0d0d12",
                "ink": "#f5f5f7",
                "muted": "#aaa9b6",
                "accent": "#00f5d4",
                "accent_strong": "#ff006e",
                "border": "#262631",
                "success": "#8ac926",
                "grid": "rgba(245, 245, 247, 0.06)",
                "bg_top": "#1a1030",
                "bg_mid": "#09090b",
                "bg_bottom": "#050507",
                "header_bg": "color-mix(in srgb, #0d0d12 90%, transparent)",
                "menu_bg": "rgba(17, 17, 23, 0.97)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.45)",
            },
            "light": {
                "bg": "#fbfbff",
                "panel": "#ffffff",
                "panel_alt": "#fbfaff",
                "ink": "#251a35",
                "muted": "#73658a",
                "accent": "#6d28d9",
                "accent_strong": "#ec4899",
                "border": "#e7def5",
                "success": "#5aa212",
                "grid": "rgba(37, 26, 53, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fcfbff",
                "bg_bottom": "#fbfbff",
                "header_bg": "color-mix(in srgb, #fbfaff 92%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(37, 26, 53, 0.12)",
            },
        },
    },
    {
        "key": "iowa_state",
        "label": "Iowa State",
        "palette": (
            "#c8102e",
            "#f1be48",
            "#862633",
            "#524727",
            "#9b9b9b",
            "#ffffff",
            "#7c2529",
            "#d1495b",
            "#edae49",
            "#6f1d1b",
        ),
        "ui": {
            "dark": {
                "bg": "#170c0f",
                "panel": "#231216",
                "panel_alt": "#1b0e12",
                "ink": "#fff5f6",
                "muted": "#d4b6bc",
                "accent": "#c8102e",
                "accent_strong": "#f1be48",
                "border": "#4a232b",
                "success": "#89c67c",
                "grid": "rgba(255, 245, 246, 0.08)",
                "bg_top": "#3a131b",
                "bg_mid": "#170c0f",
                "bg_bottom": "#0f0709",
                "header_bg": "color-mix(in srgb, #1b0e12 92%, transparent)",
                "menu_bg": "rgba(35, 18, 22, 0.98)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.42)",
            },
            "light": {
                "bg": "#fff8f8",
                "panel": "#ffffff",
                "panel_alt": "#fff1f3",
                "ink": "#3a1118",
                "muted": "#7a4b53",
                "accent": "#b10f29",
                "accent_strong": "#8d0c21",
                "border": "#f0d6dc",
                "success": "#3f8f5d",
                "grid": "rgba(58, 17, 24, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#fff5f6",
                "bg_bottom": "#fff8f8",
                "header_bg": "color-mix(in srgb, #fff1f3 94%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.99)",
                "menu_shadow": "0 16px 30px rgba(58, 17, 24, 0.12)",
            },
        },
    },
    {
        "key": "windows_xp",
        "label": "Windows XP",
        "font_family": '"Trebuchet MS", "Verdana", "Segoe UI", sans-serif',
        "palette": (
            "#245edb",
            "#3a6ee8",
            "#5fa8ff",
            "#7bc67b",
            "#f3c14b",
            "#f28c28",
            "#d9544f",
            "#7b68ee",
            "#3bb3c3",
            "#8bbf5a",
        ),
        "ui": {
            "dark": {
                "bg": "#0b2347",
                "panel": "#12325f",
                "panel_alt": "#0e294f",
                "ink": "#eef6ff",
                "muted": "#b8c9e5",
                "accent": "#5fa8ff",
                "accent_strong": "#f3c14b",
                "border": "#2d4f86",
                "success": "#7bc67b",
                "grid": "rgba(238, 246, 255, 0.08)",
                "bg_top": "#2f6fd6",
                "bg_mid": "#0b2347",
                "bg_bottom": "#07172f",
                "header_bg": "color-mix(in srgb, #0e294f 90%, transparent)",
                "menu_bg": "rgba(18, 50, 95, 0.98)",
                "menu_shadow": "0 18px 42px rgba(0, 20, 60, 0.45)",
            },
            "light": {
                "bg": "#eaf3ff",
                "panel": "#ffffff",
                "panel_alt": "#f4f9ff",
                "ink": "#12325f",
                "muted": "#5c79a5",
                "accent": "#245edb",
                "accent_strong": "#1a49ab",
                "border": "#c7dbf8",
                "success": "#4e9e5d",
                "grid": "rgba(18, 50, 95, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f2f8ff",
                "bg_bottom": "#eaf3ff",
                "header_bg": "color-mix(in srgb, #f4f9ff 94%, transparent)",
                "menu_bg": "rgba(255, 255, 255, 0.99)",
                "menu_shadow": "0 16px 30px rgba(18, 50, 95, 0.16)",
            },
        },
    },
    {
        "key": "hacker",
        "label": "Hacker",
        "font_family": '"IBM Plex Mono", "Cascadia Code", "Fira Code", "Consolas", monospace',
        "palette": (
            "#00ff41",
            "#00e5ff",
            "#ff3af2",
            "#ffd400",
            "#ff6b00",
            "#8b5cf6",
            "#39ff14",
            "#ff4d6d",
            "#00cc66",
            "#7dff7a",
        ),
        "ui": {
            "dark": {
                "bg": "#020503",
                "panel": "#07100a",
                "panel_alt": "#040b06",
                "ink": "#b7ffbf",
                "muted": "#5fbf74",
                "accent": "#00ff41",
                "accent_strong": "#39ff14",
                "border": "#12351b",
                "success": "#7dff7a",
                "grid": "rgba(0, 255, 65, 0.14)",
                "bg_top": "#08140b",
                "bg_mid": "#020503",
                "bg_bottom": "#010301",
                "header_bg": "color-mix(in srgb, #040b06 92%, transparent)",
                "menu_bg": "rgba(7, 16, 10, 0.98)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.5)",
            },
            "light": {
                "bg": "#f3fff5",
                "panel": "#fbfffb",
                "panel_alt": "#eefbf0",
                "ink": "#0b2b12",
                "muted": "#3e7c4b",
                "accent": "#0f8f3a",
                "accent_strong": "#0a6f2d",
                "border": "#cfead4",
                "success": "#15803d",
                "grid": "rgba(11, 43, 18, 0.08)",
                "bg_top": "#ffffff",
                "bg_mid": "#f6fff7",
                "bg_bottom": "#eff9f1",
                "header_bg": "color-mix(in srgb, #eefbf0 94%, transparent)",
                "menu_bg": "rgba(251, 255, 251, 0.99)",
                "menu_shadow": "0 16px 30px rgba(11, 43, 18, 0.12)",
            },
        },
    },
    {
        "key": "emacs",
        "label": "Emacs",
        "font_family": '"Space Grotesk", "IBM Plex Sans", "Segoe UI", sans-serif',
        "palette": (
            "#4db6ff",
            "#ffd84d",
            "#ff8fab",
            "#7bd389",
            "#7c83fd",
            "#ffb86b",
            "#66d9e8",
            "#ffe066",
            "#95d5b2",
            "#b197fc",
        ),
        "ui": {
            "dark": {
                "bg": "#0e2038",
                "panel": "#163252",
                "panel_alt": "#112846",
                "ink": "#f7fbff",
                "muted": "#bfd5ef",
                "accent": "#4db6ff",
                "accent_strong": "#ffd84d",
                "border": "#33557e",
                "success": "#7bd389",
                "grid": "rgba(247, 251, 255, 0.1)",
                "bg_top": "#4db6ff",
                "bg_mid": "#21446d",
                "bg_bottom": "#0e2038",
                "header_bg": "color-mix(in srgb, #163252 86%, transparent)",
                "menu_bg": "rgba(22, 50, 82, 0.97)",
                "menu_shadow": "0 18px 42px rgba(5, 24, 48, 0.34)",
            },
            "light": {
                "bg": "#eef8ff",
                "panel": "#ffffff",
                "panel_alt": "#f8fcff",
                "ink": "#17304d",
                "muted": "#5f7b98",
                "accent": "#2fa8ff",
                "accent_strong": "#f2c94c",
                "border": "#cfe6fb",
                "success": "#4caf7a",
                "grid": "rgba(23, 48, 77, 0.08)",
                "bg_top": "#87ceeb",
                "bg_mid": "#dff4ff",
                "bg_bottom": "#fff7cc",
                "header_bg": "color-mix(in srgb, #ffffff 72%, #87ceeb 28%)",
                "menu_bg": "rgba(255, 255, 255, 0.98)",
                "menu_shadow": "0 16px 30px rgba(47, 91, 142, 0.14)",
            },
        },
    },
    {
        "key": "vim",
        "label": "VIM",
        "font_family": '"IBM Plex Mono", "Cascadia Code", "Fira Code", "Consolas", monospace',
        "palette": (
            "#6e6e6e",
            "#818181",
            "#5f5f5f",
            "#929292",
            "#4f4f4f",
            "#a3a3a3",
            "#747474",
            "#585858",
            "#8a8a8a",
            "#666666",
        ),
        "ui": {
            "dark": {
                "bg": "#000000",
                "panel": "#060606",
                "panel_alt": "#0a0a0a",
                "ink": "#b5b5b5",
                "muted": "#7f7f7f",
                "accent": "#8d8d8d",
                "accent_strong": "#c2c2c2",
                "border": "#202020",
                "success": "#9a9a9a",
                "grid": "rgba(255, 255, 255, 0.06)",
                "bg_top": "#050505",
                "bg_mid": "#000000",
                "bg_bottom": "#000000",
                "header_bg": "rgba(0, 0, 0, 0.96)",
                "menu_bg": "rgba(8, 8, 8, 0.99)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.5)",
            },
            "light": {
                "bg": "#000000",
                "panel": "#060606",
                "panel_alt": "#0a0a0a",
                "ink": "#b5b5b5",
                "muted": "#7f7f7f",
                "accent": "#8d8d8d",
                "accent_strong": "#c2c2c2",
                "border": "#202020",
                "success": "#9a9a9a",
                "grid": "rgba(255, 255, 255, 0.06)",
                "bg_top": "#050505",
                "bg_mid": "#000000",
                "bg_bottom": "#000000",
                "header_bg": "rgba(0, 0, 0, 0.96)",
                "menu_bg": "rgba(8, 8, 8, 0.99)",
                "menu_shadow": "0 18px 42px rgba(0, 0, 0, 0.5)",
            },
        },
    },
    {
        "key": "high_contrast",
        "label": "High Contrast",
        "font_family": '"Space Grotesk", "IBM Plex Sans", "Segoe UI", sans-serif',
        "palette": (
            "#ffff00",
            "#00ffff",
            "#ff00ff",
            "#00ff00",
            "#ff8800",
            "#ffffff",
            "#ff3333",
            "#66ccff",
            "#ccff33",
            "#ff66cc",
        ),
        "ui": {
            "dark": {
                "bg": "#000000",
                "panel": "#080808",
                "panel_alt": "#101010",
                "ink": "#ffffff",
                "muted": "#d6d6d6",
                "accent": "#ffff00",
                "accent_strong": "#00ffff",
                "border": "#ffffff",
                "success": "#00ff00",
                "grid": "rgba(255, 255, 255, 0.22)",
                "bg_top": "#1a1a1a",
                "bg_mid": "#000000",
                "bg_bottom": "#000000",
                "header_bg": "#000000",
                "menu_bg": "rgba(0, 0, 0, 0.99)",
                "menu_shadow": "0 0 0 2px #ffffff",
            },
            "light": {
                "bg": "#ffffff",
                "panel": "#ffffff",
                "panel_alt": "#f2f2f2",
                "ink": "#000000",
                "muted": "#222222",
                "accent": "#0000ff",
                "accent_strong": "#ff00ff",
                "border": "#000000",
                "success": "#008000",
                "grid": "rgba(0, 0, 0, 0.22)",
                "bg_top": "#ffffff",
                "bg_mid": "#ffffff",
                "bg_bottom": "#f2f2f2",
                "header_bg": "#ffffff",
                "menu_bg": "rgba(255, 255, 255, 0.99)",
                "menu_shadow": "0 0 0 2px #000000",
            },
        },
    },
)

THEME_MAP = {theme["key"]: theme for theme in THEME_DEFINITIONS}


def normalize_theme_name(value: str | None) -> str:
    candidate = (value or "").strip().lower()
    return candidate if candidate in THEME_MAP else DEFAULT_THEME_NAME


def normalize_theme_mode(value: str | None) -> str:
    candidate = (value or "").strip().lower()
    return candidate if candidate in {"dark", "light"} else "dark"


def theme_palette(theme_name: str | None) -> tuple[str, ...]:
    return tuple(THEME_MAP[normalize_theme_name(theme_name)]["palette"])


def theme_label(theme_name: str | None) -> str:
    return str(THEME_MAP[normalize_theme_name(theme_name)]["label"])


def theme_interface(theme_name: str | None, theme_mode: str | None) -> dict[str, str]:
    theme = THEME_MAP[normalize_theme_name(theme_name)]
    mode = normalize_theme_mode(theme_mode)
    values = dict(DEFAULT_INTERFACE[mode])
    values.update(theme.get("ui", {}).get(mode, {}))
    return {key: str(values[key]) for key in INTERFACE_KEYS}


def palette_color(theme_name: str | None, slot_index: int | None) -> str:
    palette = theme_palette(theme_name)
    if not palette:
        return "#4cc9f0"
    try:
        index = int(slot_index or 1)
    except (TypeError, ValueError):
        index = 1
    index = max(1, min(len(palette), index))
    return palette[index - 1]


def color_slot_from_palette(theme_name: str | None, color: str | None) -> int | None:
    normalized = (color or "").strip().lower()
    if not normalized:
        return None
    for index, palette_color_value in enumerate(theme_palette(theme_name), start=1):
        if normalized == palette_color_value.lower():
            return index
    return None


def division_effective_color(division, theme_name: str | None = None) -> str:
    raw_color = (getattr(division, "color", None) or "").strip()
    if raw_color:
        return raw_color
    slot_index = getattr(division, "color_slot", None)
    return palette_color(theme_name, slot_index)
