"""add group positions

Revision ID: 26a5fff9876d
Revises: e135b28d1013
Create Date: 2026-03-16 21:12:36.494421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a5fff9876d'
down_revision = 'e135b28d1013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
    op.execute("UPDATE groups SET position = id WHERE position IS NULL OR position = 0")
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('position', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
