"""add subtask assignee

Revision ID: 363227b97e4b
Revises: cb85247191d6
Create Date: 2026-03-16 16:45:57.092949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363227b97e4b'
down_revision = 'cb85247191d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.drop_column('assignee_email')

    # ### end Alembic commands ###
