"""add assignments and invite links

Revision ID: 8b0889cf419d
Revises: 3c1702defba8
Create Date: 2026-03-16 17:04:59.189503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0889cf419d'
down_revision = '3c1702defba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create assignments table if it doesn't exist (SQLite-safe for fresh DBs)
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS assignments (
            id INTEGER NOT NULL,
            task_id INTEGER,
            subtask_id INTEGER,
            user_id INTEGER,
            email VARCHAR(255),
            status VARCHAR(50) NOT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY(subtask_id) REFERENCES subtasks (id),
            FOREIGN KEY(task_id) REFERENCES tasks (id),
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
        """
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtask_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_invites_subtask_id', 'subtasks', ['subtask_id'], ['id'])
        batch_op.create_foreign_key('fk_invites_assignment_id', 'assignments', ['assignment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invites_assignment_id', type_='foreignkey')
        batch_op.drop_constraint('fk_invites_subtask_id', type_='foreignkey')
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('assignment_id')
        batch_op.drop_column('subtask_id')

    # assignments table intentionally preserved
    # ### end Alembic commands ###
