"""add user avatar url

Revision ID: 915544c03c93
Revises: 8b0889cf419d
Create Date: 2026-03-16 18:31:57.393726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915544c03c93'
down_revision = '8b0889cf419d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
