"""add calendar opt-in defaults

Revision ID: 9eb393b0ab94
Revises: c40cd1344af8
Create Date: 2026-03-16 16:06:49.651208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb393b0ab94'
down_revision = 'c40cd1344af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_opt_in', sa.Boolean(), nullable=False))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_owner_calendar_opt_in', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('default_invitee_calendar_opt_in', sa.Boolean(), nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_calendar_opt_in', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('owner_calendar_opt_in')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('default_invitee_calendar_opt_in')
        batch_op.drop_column('default_owner_calendar_opt_in')

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('calendar_opt_in')

    # ### end Alembic commands ###
