"""add task and subtask links

Revision ID: aab743863d57
Revises: e08b5f9add29
Create Date: 2026-03-16 22:16:21.803977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab743863d57'
down_revision = 'e08b5f9add29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=1024), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('link')

    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
