"""add group color

Revision ID: c9f61b6a0aab
Revises: 26a5fff9876d
Create Date: 2026-03-16 21:18:18.742639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f61b6a0aab'
down_revision = '26a5fff9876d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=32), nullable=True))
    op.execute(
        """
        UPDATE groups
        SET color = CASE (id % 8)
            WHEN 0 THEN '#4cc9f0'
            WHEN 1 THEN '#7dd3fc'
            WHEN 2 THEN '#f59e0b'
            WHEN 3 THEN '#34d399'
            WHEN 4 THEN '#f472b6'
            WHEN 5 THEN '#a78bfa'
            WHEN 6 THEN '#f87171'
            ELSE '#38bdf8'
        END
        WHERE color IS NULL
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
